# Note: If you update this, make sure to update tox.ini, too.
ch: amd64
      pydist: xenial
language: python
cache:
  directories:
  - "~/.cache/pip"

matrix:
  include:
    - arch: arm64
      python: 2.7
    - arch: amd64
      python: 2.7
    - arch: arm64
      python: "2.7"
      env: MODE=lint
    - arch: amd64
      python: "2.7"
      env: MODE=lint
    - arch: arm64
      python: "2.7"
      env: MODE=vendorverify
    - arch: amd64
      python: "2.7"
      env: MODE=vendorverify
    - arch: arm64
      python: 3.4
    - arch: amd64
      python: 3.4
    - arch: arm64
      python: "3.4"
      env: MODE=lint
    - arch: amd64
      python: "3.4"
      env: MODE=lint
    - arch: arm64
      python: 3.5
    - arch: amd64
      python: 3.5
    - arch: arm64
      python: 3.6
    - arch: amd64
      python: 3.6
    - arch: arm64
      python: "3.6"
      env: MODE=docs
    - arch: arm64
      python: "3.6"
      env: MODE=docs
    - arch: arm64
      python: 3.7
    - arch: amd64
      python: 3.7
    - arch: arm64
      python: 3.8
    - arch: amd64
      python: 3.8
    - arch: amd64
      python: "pypy2.7-6.0"
    - arch: arm64
      python: "pypy2.7-6.0"      
    - arch: amd64
      python: "pypy3.5-6.0"
    - arch: arm64
      python: "pypy3.5-6.0"

install:
  - pip install -U pip setuptools>=18.5
  - pip install -r requirements-dev.txt

script:
  - ./scripts/run_tests.sh $MODE
